fields:
    service_name:
        label: 'Название услуги'
        span: auto
        required: 1
        type: text
    service_price_first:
        label: 'Цена услуги'
        span: auto
        required: 1
        type: number
    category:
        label: 'Категория услуги'
        nameFrom: id
        descriptionFrom: description
        select: category_name
        span: auto
        required: 1
        type: relation
    specialty:
        label: 'Специальность врача'
        showSearch: true
        span: auto
        placeholder: 'Кто оказывает данную услугу?'
        dependsOn:
            - category
        trigger:
            action: show
            field: category
            condition: 'value[1]'
        type: dropdown
