title: Doctors
modelClass: WDesighners\Services\Models\Doctors
list: $/wdesighners/services/models/doctors/columns.yaml
recordUrl: 'wdesighners/services/doctors/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
