list: $/wdesighners/services/models/analyzes/analizes_list.yaml
modelClass: WDesighners\Services\Models\Analyzes
title: Analyzes
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'wdesighners/services/analyzes/update/:id'
