list: $/wdesighners/services/models/analysiscategories/analysis_categories_list.yaml
modelClass: WDesighners\Services\Models\AnalysisCategories
title: AnalisisCategories
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'wdesighners/services/analisiscategories/update/:id'
